apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drift-detector.fullname" . }}-config
  labels:
    {{- include "drift-detector.labels" . | nindent 4 }}
data:
  application-k8s.yml: |
    server:
      port: {{ .Values.service.targetPort }}
    spring:
      data:
        redis:
          host: ${REDIS_HOST}
          port: ${REDIS_PORT}
      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus
      endpoint:
        health:
          probes:
            enabled: true