server.port=8082
spring.application.name=model-registry

spring.datasource.url=jdbc:postgresql://localhost:5432/model_registry
spring.datasource.username=aiplatform
spring.datasource.password=aiplatform
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
server.address=127.0.0.1