apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: batch-processor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/toosparks/ai-inference-platform.git
    targetRevision: main
    path: infrastructure/helm/batch-processor
    helm:
      releaseName: batch-processor
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true