server.port=8081
spring.application.name=billing
spring.datasource.url=jdbc:postgresql://localhost:5432/billing
spring.datasource.username=aiplatform
spring.datasource.password=aiplatform
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=billing-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=ru.itis.billing.dto
spring.kafka.consumer.properties.spring.json.value.default.type=ru.itis.billing.dto.InferenceEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true

server.address=127.0.0.1