strategy:
  type: Recreate

replicaCount: 1

image:
  repository: ghcr.io/toosparks/model-registry
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

resources:
  requests:
    memory: "512Mi"
    cpu: "150m"
  limits:
    memory: "1024Mi"
    cpu: "700m"

startupProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 30
  timeoutSeconds: 3

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8082
  initialDelaySeconds: 0
  periodSeconds: 20
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8082
  initialDelaySeconds: 0
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"
  - name: POSTGRES_HOST
    value: "192.168.65.254"
  - name: POSTGRES_PORT
    value: "5432"
  - name: POSTGRES_DB
    value: "model_registry"

nodeSelector: {}
tolerations: []
affinity: {}